In [8]:
#To remove value from list using pop:
cities = ['bangalore','mumbai','chennai']
cities.pop(0)

'bangalore'

In [9]:
cities

['mumbai', 'chennai']

In [10]:
#To remove value from list using remove:
cities.remove('mumbai')
cities

['chennai']

In [11]:
##To remove value from list using del function:
del cities[0] 

In [12]:
cities

[]

In [34]:
dict1 = {'a':'alpha', 'b':'beta', 'c':'gamma'}
dict1.items()

In [13]:
#to get KV pair in to list 
#Method 1
dict1 = {'a':'alpha', 'b':'beta', 'c':'gamma'}
l=[]
for i in dict1.keys():
    l.append(i)
    l.append(dict1[i])
l

['a', 'alpha', 'b', 'beta', 'c', 'gamma']

In [14]:
#Method 2
dict1 = {'a':'alpha', 'b':'beta', 'c':'gamma'}
l=[]
for i in dict1.items():
    l.extend(i)
l

['a', 'alpha', 'b', 'beta', 'c', 'gamma']

In [15]:
#Method 3
dict1 = {'a':'alpha', 'b':'beta', 'c':'gamma'}
l=[]
for i,j in dict1.items():
    l.append(i)
    l.append(j)
l

['a', 'alpha', 'b', 'beta', 'c', 'gamma']

- '.' doesnot add space when concatenated
- ',' adds space when conatenated

In [48]:
import numpy as np

In [50]:
a = np.arange(1,101).reshape(10,10)

In [51]:
a.T

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [52]:
a[::-1,::-1]

array([[100,  99,  98,  97,  96,  95,  94,  93,  92,  91],
       [ 90,  89,  88,  87,  86,  85,  84,  83,  82,  81],
       [ 80,  79,  78,  77,  76,  75,  74,  73,  72,  71],
       [ 70,  69,  68,  67,  66,  65,  64,  63,  62,  61],
       [ 60,  59,  58,  57,  56,  55,  54,  53,  52,  51],
       [ 50,  49,  48,  47,  46,  45,  44,  43,  42,  41],
       [ 40,  39,  38,  37,  36,  35,  34,  33,  32,  31],
       [ 30,  29,  28,  27,  26,  25,  24,  23,  22,  21],
       [ 20,  19,  18,  17,  16,  15,  14,  13,  12,  11],
       [ 10,   9,   8,   7,   6,   5,   4,   3,   2,   1]])

In [57]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
a.mean()

5.0

In [58]:
#vertical mean in np
a.mean(0)

array([4., 5., 6.])

In [59]:
#horizontal mean in np
a.mean(1)

array([2., 5., 8.])

In [60]:
b=a+10

In [61]:
b

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

np.any()
- if any is True returns True else False

np.all()
- if all is True returns True else False

In [68]:
import pandas as pd

In [83]:
a = np.array([1,2,3,4])
b = np.array([100,200,300,400])
c = np.array([True, False,True,False])

In [88]:
np.where(c,a,b) #first argument to be boolean
#if True then a
#if False then b

array([  1, 200,   3, 400])

In [93]:
a = np.random.randint(1,101,10)
a

array([61, 61, 60, 79, 89,  3, 25, 77, 70, 66])

In [94]:
np.where(a<40) #index of value that satusfy the condition

(array([5, 6], dtype=int64),)

get date from series
1. By index, a[0]
2. By label, a['a']
3. By multiple label, a[['a','b']]
4. By range, a[0:3]
5. By logic, a[a<3]

for DF
- By column
- By multiple column
- By rows
- By logic
- .iloc -> position
- .loc -> label

In [95]:
#reindex -> to add new value

In [96]:
from pandas import Series,DataFrame #no need to write pd.
ser1 = Series(['India','Bhuthan','Nepal'],index=[1,5,10])

In [97]:
ser1

1       India
5     Bhuthan
10      Nepal
dtype: object

In [98]:
ser1.reindex(range(15))

0         NaN
1       India
2         NaN
3         NaN
4         NaN
5     Bhuthan
6         NaN
7         NaN
8         NaN
9         NaN
10      Nepal
11        NaN
12        NaN
13        NaN
14        NaN
dtype: object

In [99]:
ser1.reindex(range(15),method='ffill')

0         NaN
1       India
2       India
3       India
4       India
5     Bhuthan
6     Bhuthan
7     Bhuthan
8     Bhuthan
9     Bhuthan
10      Nepal
11      Nepal
12      Nepal
13      Nepal
14      Nepal
dtype: object

In [102]:
ser1.reindex(range(15),method='bfill')

0       India
1       India
2     Bhuthan
3     Bhuthan
4     Bhuthan
5     Bhuthan
6       Nepal
7       Nepal
8       Nepal
9       Nepal
10      Nepal
11        NaN
12        NaN
13        NaN
14        NaN
dtype: object

In [103]:
ser1.reindex(range(15),method='nearest')

0       India
1       India
2       India
3     Bhuthan
4     Bhuthan
5     Bhuthan
6     Bhuthan
7     Bhuthan
8       Nepal
9       Nepal
10      Nepal
11      Nepal
12      Nepal
13      Nepal
14      Nepal
dtype: object

In [104]:
s = ser1.reindex(range(15))

In [105]:
s

0         NaN
1       India
2         NaN
3         NaN
4         NaN
5     Bhuthan
6         NaN
7         NaN
8         NaN
9         NaN
10      Nepal
11        NaN
12        NaN
13        NaN
14        NaN
dtype: object

In [106]:
s.fillna('Pak')

0         Pak
1       India
2         Pak
3         Pak
4         Pak
5     Bhuthan
6         Pak
7         Pak
8         Pak
9         Pak
10      Nepal
11        Pak
12        Pak
13        Pak
14        Pak
dtype: object

In [107]:
s.fillna(method='ffill')

0         NaN
1       India
2       India
3       India
4       India
5     Bhuthan
6     Bhuthan
7     Bhuthan
8     Bhuthan
9     Bhuthan
10      Nepal
11      Nepal
12      Nepal
13      Nepal
14      Nepal
dtype: object

In [108]:
s.fillna(method='bfill')

0       India
1       India
2     Bhuthan
3     Bhuthan
4     Bhuthan
5     Bhuthan
6       Nepal
7       Nepal
8       Nepal
9       Nepal
10      Nepal
11        NaN
12        NaN
13        NaN
14        NaN
dtype: object